### PR TITLE
Bump IDEA to 2023.2.3

### PR DESCRIPTION
**Pull request by Blackburn29**

### CODE REVIEW

**Review by jayofdoom — CHANGES_REQUESTED** [review]
You need to change the build number in the ebuild.

the line should be:
`BUILD_NUMBER="232.10072.27"` 

This change makes the ebuild work.

**Comment by Blackburn29** [comment]
> You need to change the build number in the ebuild.
> 
> the line should be: `BUILD_NUMBER="232.10072.27"`
> 
> This change makes the ebuild work.

Apologies, I updated this in a rush and forgot to add that. It also looks like they've updated the download URI so I went ahead and changed that as well.

**Comment by jayofdoom** [comment]
Oh, interesting. Old URL worked for the update last night with the new ebuild.

**Comment by jayofdoom** [comment]
Not going to bother making a PR since I'm unsure if it'll merge; but maybe this'll make your (or someone's) life easier for 2023.2.4...

`BUILD_NUMBER=232.10203.10`

The ebuild in PR works when copied over without change otherwise.

**Comment by ffjdm** [comment]
The download-cdn url looks like a technical url for AWS CloudFront. Perhaps it would be safer to keep the actual one?

**Comment by Blackburn29** [comment]
I'm going to close this in favor of https://github.com/bombo82/bombo82-overlay/pull/21

**Pull request closed without merging**
